Repository GeraAlcantara/cards-memory-game, pull requests merged in 2022-10, with the labels that each got.

#2 VanillajsGame
  gameBase/README.md
  gameBase/index.html
  gameBase/src/css/styles.css
  gameBase/src/img/angular.svg
  gameBase/src/img/ember.svg
  gameBase/src/img/js-badge.svg
  gameBase/src/img/node.svg
  gameBase/src/img/react.svg
  gameBase/src/img/svelte.svg
  gameBase/src/img/vue.svg
  gameBase/src/js/main.js
Labels: hacktoberfest-accepted

#12 adding docs forder for gitpages
  docs/README.md
  docs/index.html
  docs/src/css/styles.css
  docs/src/img/angular.svg
  docs/src/img/ember.svg
  docs/src/img/js-badge.svg
  docs/src/img/node.svg
  docs/src/img/react.svg
  docs/src/img/svelte.svg
  docs/src/img/vue.svg
  docs/src/js/main.js
Labels: hacktoberfest-accepted

#11 Add missing quotation mark to fix issue #7
  gameBase/index.html
Labels: hacktoberfest-accepted

#10 Port base game to React (Issue #3)
  .gitignore
  React/react-memory-game/README.md
  React/react-memory-game/package-lock.json
  React/react-memory-game/package.json
  React/react-memory-game/public/favicon.ico
  React/react-memory-game/public/index.html
  React/react-memory-game/public/logo192.png
  React/react-memory-game/public/logo512.png
  React/react-memory-game/public/manifest.json
  React/react-memory-game/public/robots.txt
  React/react-memory-game/src/App.js
  React/react-memory-game/src/components/MemoryCard.js
  React/react-memory-game/src/css/styles.css
  React/react-memory-game/src/img/angular.svg
  React/react-memory-game/src/img/blank.svg
  React/react-memory-game/src/img/ember.svg
  React/react-memory-game/src/img/js-badge.svg
  React/react-memory-game/src/img/node.svg
  React/react-memory-game/src/img/react.svg
  React/react-memory-game/src/img/svelte.svg
  React/react-memory-game/src/img/vue.svg
  React/react-memory-game/src/index.js
Labels: hacktoberfest-accepted

#8 Add Readme in portugues
  README(pt_BR).md
Labels: hacktoberfest-accepted

#13 update readme to spanish
  translation/README[ES_MX].md
Labels: hacktoberfest-accepted

#21 create base for vue game version
  VUE/.gitignore
  VUE/README.md
  VUE/index.html
  VUE/package-lock.json
  VUE/package.json
  VUE/public/favicon.ico
  VUE/src/.prettierrc
  VUE/src/App.vue
  VUE/src/assets/gameBase/README.md
  VUE/src/assets/gameBase/index.html
  VUE/src/assets/gameBase/src/css/styles.css
  VUE/src/assets/gameBase/src/img/angular.svg
  VUE/src/assets/gameBase/src/img/ember.svg
  VUE/src/assets/gameBase/src/img/js-badge.svg
  VUE/src/assets/gameBase/src/img/node.svg
  VUE/src/assets/gameBase/src/img/react.svg
  VUE/src/assets/gameBase/src/img/svelte.svg
  VUE/src/assets/gameBase/src/img/vue.svg
  VUE/src/assets/gameBase/src/js/main.js
  VUE/src/assets/logo.svg
  VUE/src/assets/main.css
  VUE/src/game.js
  VUE/src/main.js
  VUE/src/router/index.js
  VUE/src/views/GameView.vue
  VUE/vite.config.js
Labels: hacktoberfest-accepted

#25 React code fixes and enhancements
  React/src/App.js
  React/src/components/MemoryCard.js
  React/src/helper/shuffle.js
Labels: hacktoberfest-accepted

#26 Translation PT-BR
  translation/README[PT_BR].md
Labels: hacktoberfest-accepted

#27 Refactored VUE and implemented game using native VueJS
  VUE/index.html
  VUE/package-lock.json
  VUE/package.json
  VUE/src/App.vue
  VUE/src/assets/gameBase/README.md
  VUE/src/assets/gameBase/index.html
  VUE/src/assets/gameBase/src/css/styles.css
  VUE/src/assets/gameBase/src/js/main.js
  VUE/src/assets/img/angular.svg
  VUE/src/assets/img/ember.svg
  VUE/src/assets/img/js-badge.svg
  VUE/src/assets/img/node.svg
  VUE/src/assets/img/react.svg
  VUE/src/assets/img/svelte.svg
  VUE/src/assets/img/vue.svg
  VUE/src/assets/main.css
  VUE/src/components/CardComponent.vue
  VUE/src/game.js
  VUE/src/main.js
  VUE/src/views/GameView.vue
Labels: hacktoberfest-accepted

#24 Add implementation with React TypeScript
  TypeScript/TypeScript-React/.gitignore
  TypeScript/TypeScript-React/GUIDELINES.md
  TypeScript/TypeScript-React/README.md
  TypeScript/TypeScript-React/index.html
  TypeScript/TypeScript-React/package-lock.json
  TypeScript/TypeScript-React/package.json
  TypeScript/TypeScript-React/public/vite.svg
  TypeScript/TypeScript-React/src/App.css
  TypeScript/TypeScript-React/src/App.tsx
  TypeScript/TypeScript-React/src/assets/angular.svg
  TypeScript/TypeScript-React/src/assets/ember.svg
  TypeScript/TypeScript-React/src/assets/js-badge.svg
  TypeScript/TypeScript-React/src/assets/node.svg
  TypeScript/TypeScript-React/src/assets/react.svg
  TypeScript/TypeScript-React/src/assets/svelte.svg
  TypeScript/TypeScript-React/src/assets/vue.svg
  TypeScript/TypeScript-React/src/components/MemoryCard.tsx
  TypeScript/TypeScript-React/src/data/items.ts
  TypeScript/TypeScript-React/src/helpers/shuffle.ts
  TypeScript/TypeScript-React/src/main.tsx
  TypeScript/TypeScript-React/src/ts/item.interface.ts
  TypeScript/TypeScript-React/src/ts/props.interface.ts
  TypeScript/TypeScript-React/src/vite-env.d.ts
  TypeScript/TypeScript-React/tsconfig.json
  TypeScript/TypeScript-React/tsconfig.node.json
  TypeScript/TypeScript-React/vite.config.ts
Labels: hacktoberfest-accepted

#29 fixing draggable images
  gameBase/src/js/main.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#35 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#43 Update to Readme.md and Removed code_of_conduct
  CODE_OF_CONDUCT.MD
  CODE_OF_CONDUCT.md
  README.md
Labels: Hacktoberfest2022

#42 Issue #38 Fixed card remains flipped when card was double clicked bot…
  VUE/src/views/GameView.vue
Labels: hacktoberfest-accepted

#45 fixes the card flipped bug from react app
  React/src/App.js
Labels: Hacktoberfest2022

#49 Added favicon.png to repo as well as code to index.html to display favicon
  docs/index.html
  docs/src/img/favicon.png
Labels: hacktoberfest-accepted

#57 Adding description in metatag
  gameBase/index.html
Labels: hacktoberfest-accepted

#59 added other changes to make responsive
  docs/src/css/styles.css
  gameBase/src/css/styles.css
Labels: hacktoberfest-accepted

#60 add NON_CODE_CONTRIBUTIONS and EXAMPLES files
  NON_CODE_CONTRIBUTIONS/EXAMPLES.md
  NON_CODE_CONTRIBUTIONS/NON_CODE_CONTRIBUTIONS.md
Labels: hacktoberfest-accepted

#61 [Fix] card hover in devices with no hover #52
  gameBase/src/css/styles.css
Labels: hacktoberfest-accepted
